# Main Configuration File for AmberBot
# You can find messages that appear in the MC Chat in messages.yml
# You can find messages that appear in the Discord Chat in messages.yml
# To configure in which channels the bot should do stuff in look @ channels.yml
# To setup this Bot please visit the Tutorial on our GitHub.
Token: 'Insert Token For Dicord Bot Here :)'
Game: 'MineCraft'
Command-Prefix: '~'
log-discord-commands-to-mc-log: false # You can see which discord commands are run in the MC Console.